menu:
  首頁: / || fas fa-home
  時間軸: /archives/ || fas fa-archive

highlight_theme: pale night
highlight_copy: true

social:
  fab fa-github: https://github.com/836334258 || Github
  fas fa-envelope: mailto:836334258@qq.com || Email

cover:
  # 是否顯示文章封面
  index_enable: true
  aside_enable: true
  archives_enable: true
  # 封面顯示的位置
  # 三個值可配置 left , right , both
  position: both
  # 當沒有設置cover時，默認的封面顯示
  default_cover:
    - https://cdn.jsdelivr.net/gh/jerryc127/CDN@latest/cover/default_bg.png
    - https://cdn.jsdelivr.net/gh/jerryc127/CDN@latest/cover/default_bg2.png
    - https://cdn.jsdelivr.net/gh/jerryc127/CDN@latest/cover/default_bg3.png

post_meta:
  page:
    date_type: both # created or updated or both 主頁文章日期是創建日或者更新日或都顯示
    date_format: relative # date/relative 顯示日期還是相對日期
    categories: true # true or false 主頁是否顯示分類
    tags: true # true or false 主頁是否顯示標籤
    label: true # true or false 顯示描述性文字
  post:
    date_type: both # created or updated or both 文章頁日期是創建日或者更新日或都顯示
    date_format: relative # date/relative 顯示日期還是相對日期
    categories: true # true or false 文章頁是否顯示分類
    tags: true # true or false 文章頁是否顯示標籤
    label: true # true or false 顯示描述性文字

reward:
  enable: true
  QR_code:
    - img: /img/wechat.jpeg
      link:
      text: 微信
    - img: /img/alipay.jpeg
      link:
      text: 支付宝
toc:
  enable: true
  number: true
  style_simple: true

related_post:
  enable: true
  limit: 6 # 顯示推薦文章數目
  date_type: created # or created or updated 文章日期顯示創建日或者更新日

footer:
  owner:
    enable: true
    since: 2021
# dark mode
darkmode:
  enable: true
  # dark mode和 light mode切換按鈕
  button: true
  autoChangeMode: true
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

runtimeshow:
  enable: true
  publish_date: 2/23/2021 00:00:00
  ##網頁開通時間
  #格式: 月/日/年 時間
  #也可以寫成 年/月/日 時間
comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo
  use:
    - Valine
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: true
  count: true # Display comment count in top_img
  card_post_count: false # Display comment count in Home Page

# Aside widget - Newest Comments
#newest_comments:
#  enable: true
#  sort_order: # Don't modify the setting unless you know how it works
#  limit: 6
#  storage: 10 # unit: mins, save data to localStorage
#  avatar: true
#  # You can only choose one, or neither
#  valine: true
#  github_issues:
#    enable: false
#    repo:
#  disqus:
#    enable: false
#    forum:
#    api_key:
#  twikoo: false
#  waline: false


note:
  # Note tag style values:
  #  - simple    bs-callout old alert style. Default.
  #  - modern    bs-callout new (v2-v3) alert style.
  #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
  #  - disabled  disable all CSS styles import of note tag.
  style: simple
  icons: false
  border_radius: 3
  # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
  # Offset also applied to label tag variables. This option can work with disabled note tag.
  light_bg_offset: 0

custom_text: '备案号： <a href="https://beian.miit.gov.cn/" target="_blank">浙ICP备19007985号</a>!'

baidu_analytics: 'https://hm.baidu.com/hm.js?e261df6dfda9f69a5d48180d04b76d4e'

canvas_ribbon:
  enable: true
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false  #設置是否每次點擊都更換綵帶
  mobile: false # false 手機端不顯示 true 手機端顯示
#
fireworks:
  enable: true
  zIndex: 9999 # -1 or 9999
  mobile: false

#wordcount:
#  enable: true
#  post_wordcount: true
#  min2read: true
#  total_wordcount: true

# fancybox http://fancyapps.com/fancybox/3/
fancybox: true